# Generated by Django 4.2.19 on 2025-02-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_alter_corporation_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticker_name', models.CharField(max_length=10)),
                ('stocks_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sold', models.BooleanField(default=False)),
            ],
        ),
    ]
