# Generated by Django 4.2.19 on 2025-02-20 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_remove_investment_sold_remove_investment_ticker_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
