# Generated by Django 4.2.19 on 2025-02-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_alter_corporation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='total_investment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
