# Generated by Django 4.2.19 on 2025-02-24 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_usuario_investment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='total_investment',
        ),
        migrations.AlterField(
            model_name='investment',
            name='corporation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='stocks.corporation'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='stocks.usuario'),
        ),
    ]
