# Generated by Django 4.2.19 on 2025-02-24 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0010_alter_usuario_email_alter_usuario_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='name',
            new_name='username',
        ),
    ]
