# Generated by Django 4.2.19 on 2025-02-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0011_rename_name_usuario_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
